-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema datamart_airbnb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datamart_airbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datamart_airbnb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `datamart_airbnb` ;

-- -----------------------------------------------------
-- Table `datamart_airbnb`.`user_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`user_language` (
  `language_id` INT NOT NULL,
  `language` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`users` (
  `user_id` INT NOT NULL COMMENT 'Unique identifier for user',
  `username` VARCHAR(255) NOT NULL COMMENT 'Unique username generated by user',
  `firstname` VARCHAR(255) NOT NULL COMMENT 'First name of the user',
  `lastname` VARCHAR(255) NOT NULL COMMENT 'Last name of the user',
  `email` VARCHAR(255) NOT NULL COMMENT 'Unique email adress of the user',
  `phone` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Phone number of the user',
  `password` VARCHAR(255) NOT NULL COMMENT 'Encrypted password generated by the user',
  `profile_img` INT NULL DEFAULT NULL,
  `about_me` TEXT NULL DEFAULT NULL,
  `user_role` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP GENERATED ALWAYS AS (),
  `permission_set_id` INT NOT NULL,
  `user_language_language_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_user_language1_idx` (`user_language_language_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_language1`
    FOREIGN KEY (`user_language_language_id`)
    REFERENCES `datamart_airbnb`.`user_language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`administration` (
  `admin_id` INT NOT NULL,
  `access_level` VARCHAR(255) NULL DEFAULT NULL,
  `access_level_id` INT NULL DEFAULT NULL,
  `operations` VARCHAR(255) NULL DEFAULT NULL,
  `user_roles` VARCHAR(255) NULL DEFAULT NULL,
  `users_user_id` INT NOT NULL,
  `user_language_language_id` INT NOT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `fk_administration_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_administration_user_language1_idx` (`user_language_language_id` ASC) VISIBLE,
  CONSTRAINT `fk_administration_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `datamart_airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administration_user_language1`
    FOREIGN KEY (`user_language_language_id`)
    REFERENCES `datamart_airbnb`.`user_language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`property_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`property_category` (
  `property_category_id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`property_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`property` (
  `property_id` INT NOT NULL,
  `property_type` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `room_size` VARCHAR(255) NULL DEFAULT NULL,
  `room_rate` DECIMAL(10,0) NULL DEFAULT NULL,
  `availability` TINYINT(1) NULL DEFAULT NULL,
  `property_category_property_category_id` INT NOT NULL,
  PRIMARY KEY (`property_id`),
  INDEX `fk_property_property_category1_idx` (`property_category_property_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_property_category1`
    FOREIGN KEY (`property_category_property_category_id`)
    REFERENCES `datamart_airbnb`.`property_category` (`property_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`room` (
  `room_id` INT NOT NULL,
  `property_id` INT NULL DEFAULT NULL,
  `room_status` VARCHAR(255) NULL DEFAULT NULL,
  `property_property_id` INT NOT NULL,
  INDEX `fk_room_property1_idx` (`property_property_id` ASC) VISIBLE,
  PRIMARY KEY (`room_id`),
  CONSTRAINT `fk_room_property1`
    FOREIGN KEY (`property_property_id`)
    REFERENCES `datamart_airbnb`.`property` (`property_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`amenity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`amenity` (
  `amenity_id` INT NOT NULL,
  `amenity_name` VARCHAR(255) NULL DEFAULT NULL,
  `amenity_category` VARCHAR(255) NULL DEFAULT NULL,
  `amenity_category_id` INT NULL DEFAULT NULL,
  `property_property_id` INT NOT NULL,
  `room_room_id` INT NOT NULL,
  PRIMARY KEY (`amenity_id`),
  INDEX `fk_amenity_property1_idx` (`property_property_id` ASC) VISIBLE,
  INDEX `fk_amenity_room1_idx` (`room_room_id` ASC) VISIBLE,
  CONSTRAINT `fk_amenity_property1`
    FOREIGN KEY (`property_property_id`)
    REFERENCES `datamart_airbnb`.`property` (`property_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_amenity_room1`
    FOREIGN KEY (`room_room_id`)
    REFERENCES `datamart_airbnb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`payment` (
  `payment_id` INT NOT NULL,
  `payment_status` VARCHAR(255) NULL DEFAULT NULL,
  `transaction_date` DOUBLE NULL DEFAULT NULL,
  `due_date` DATETIME NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`, `user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`messages` (
  `message_id` INT NOT NULL,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NULL,
  `text` VARCHAR(255) NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_messages_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `datamart_airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`guest` (
  `user_id` INT NOT NULL,
  `guest_id` INT NOT NULL,
  `guest_type` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `messages_message_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_guest_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_guest_messages1_idx` (`messages_message_id` ASC) VISIBLE,
  CONSTRAINT `fk_guest_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `datamart_airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guest_messages1`
    FOREIGN KEY (`messages_message_id`)
    REFERENCES `datamart_airbnb`.`messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`booking` (
  `booking_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `guest_id` INT NULL DEFAULT NULL,
  `booking_id` INT NULL DEFAULT NULL,
  `propoerty_id` INT NULL DEFAULT NULL,
  `chat_id` INT NULL DEFAULT NULL,
  `booking_price` DOUBLE NULL DEFAULT NULL,
  `daily_rate` DOUBLE NULL DEFAULT NULL,
  `num_of_days` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `payment_user_id` INT NOT NULL,
  `guest_user_id` INT NOT NULL,
  `property_property_id` INT NOT NULL,
  INDEX `fk_booking_payment1_idx` (`payment_user_id` ASC) VISIBLE,
  INDEX `fk_booking_guest1_idx` (`guest_user_id` ASC) VISIBLE,
  INDEX `fk_booking_property1_idx` (`property_property_id` ASC) VISIBLE,
  PRIMARY KEY (`booking_id`),
  CONSTRAINT `booking_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `datamart_airbnb`.`users` (`user_id`),
  CONSTRAINT `fk_booking_payment1`
    FOREIGN KEY (`payment_user_id`)
    REFERENCES `datamart_airbnb`.`payment` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_guest1`
    FOREIGN KEY (`guest_user_id`)
    REFERENCES `datamart_airbnb`.`guest` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_property1`
    FOREIGN KEY (`property_property_id`)
    REFERENCES `datamart_airbnb`.`property` (`property_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`host` (
  `host_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `messages_message_id` INT NOT NULL,
  INDEX `fk_host_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_host_messages1_idx` (`messages_message_id` ASC) VISIBLE,
  PRIMARY KEY (`host_id`),
  CONSTRAINT `fk_host_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `datamart_airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_host_messages1`
    FOREIGN KEY (`messages_message_id`)
    REFERENCES `datamart_airbnb`.`messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`country` (
  `country_id` INT NOT NULL,
  `country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`location` (
  `location_id` INT NOT NULL,
  `continent` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `adress` VARCHAR(255) NULL DEFAULT NULL,
  `property_property_id` INT NOT NULL,
  `country_country_id` INT NOT NULL,
  PRIMARY KEY (`location_id`),
  INDEX `fk_location_property1_idx` (`property_property_id` ASC) VISIBLE,
  INDEX `fk_location_country1_idx` (`country_country_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_property1`
    FOREIGN KEY (`property_property_id`)
    REFERENCES `datamart_airbnb`.`property` (`property_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_country1`
    FOREIGN KEY (`country_country_id`)
    REFERENCES `datamart_airbnb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`rating` (
  `rating_id` INT NOT NULL,
  `guest_id` INT NULL DEFAULT NULL,
  `created_on` TIMESTAMP NULL DEFAULT NULL,
  `stars` INT NULL DEFAULT NULL,
  `bodytext` TEXT NULL DEFAULT NULL COMMENT 'Content of the rating',
  `property_property_id` INT NOT NULL,
  `guest_user_id` INT NOT NULL,
  INDEX `fk_rating_property1_idx` (`property_property_id` ASC) VISIBLE,
  PRIMARY KEY (`rating_id`),
  INDEX `fk_rating_guest1_idx` (`guest_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_rating_property1`
    FOREIGN KEY (`property_property_id`)
    REFERENCES `datamart_airbnb`.`property` (`property_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_guest1`
    FOREIGN KEY (`guest_user_id`)
    REFERENCES `datamart_airbnb`.`guest` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`reservation` (
  `reservation_id` INT NULL,
  `user_id` INT NOT NULL,
  `reservation_date` DATETIME NULL DEFAULT NULL,
  `timestamp_checkin` DATETIME NULL DEFAULT NULL,
  `reservation_id` DATETIME NULL DEFAULT NULL,
  `free_cancelation_date` DATETIME NULL DEFAULT NULL,
  `cancelation_id` INT NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `booking_user_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`, `user_id`),
  INDEX `fk_reservation_booking1_idx` (`booking_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_booking1`
    FOREIGN KEY (`booking_user_id`)
    REFERENCES `datamart_airbnb`.`booking` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`permission` (
  `permission_set_id` INT NULL,
  `create_user` TINYINT NULL,
  `view_user` TINYINT NULL,
  `update_user` TINYINT NULL,
  `delete_user` TINYINT NULL,
  `administration_admin_id` INT NOT NULL,
  PRIMARY KEY (`permission_set_id`),
  INDEX `fk_permission_administration1_idx` (`administration_admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_permission_administration1`
    FOREIGN KEY (`administration_admin_id`)
    REFERENCES `datamart_airbnb`.`administration` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`access_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`access_level` (
  `access_id` INT NOT NULL,
  `access_level` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `administration_admin_id` INT NOT NULL,
  PRIMARY KEY (`access_id`),
  INDEX `fk_access_level_administration1_idx` (`administration_admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_access_level_administration1`
    FOREIGN KEY (`administration_admin_id`)
    REFERENCES `datamart_airbnb`.`administration` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`user_group` (
  `user_group_id` INT NULL,
  `user_group_permission_id` INT NULL,
  `permission_set_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `access_level_access_id` INT NOT NULL,
  INDEX `fk_user_group_permission1_idx` (`permission_set_id` ASC) VISIBLE,
  INDEX `fk_user_group_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_group_access_level1_idx` (`access_level_access_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_group_permission1`
    FOREIGN KEY (`permission_set_id`)
    REFERENCES `datamart_airbnb`.`permission` (`permission_set_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_group_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `datamart_airbnb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_group_access_level1`
    FOREIGN KEY (`access_level_access_id`)
    REFERENCES `datamart_airbnb`.`access_level` (`access_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`voucher` (
  `voucher_id` INT NOT NULL,
  `voucher_code` VARCHAR(45) NULL,
  `voucher_due_date` DATE NULL,
  `created_at` DATE NULL,
  `payment_payment_id` INT NOT NULL,
  `payment_user_id` INT NOT NULL,
  INDEX `fk_voucher_payment1_idx` (`payment_payment_id` ASC, `payment_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_voucher_payment1`
    FOREIGN KEY (`payment_payment_id` , `payment_user_id`)
    REFERENCES `datamart_airbnb`.`payment` (`payment_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`social media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`social media` (
  `platfrom_id` INT NOT NULL,
  `social_media_type` VARCHAR(45) NULL,
  `platform_name` VARCHAR(45) NULL,
  `account_url` VARCHAR(45) NULL,
  `guest_user_id` INT NOT NULL,
  PRIMARY KEY (`platfrom_id`),
  INDEX `fk_social media_guest1_idx` (`guest_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_social media_guest1`
    FOREIGN KEY (`guest_user_id`)
    REFERENCES `datamart_airbnb`.`guest` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`payment type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`payment type` (
  `payment_id` INT NOT NULL,
  `payment_type` VARCHAR(45) NULL,
  `bank account_url` VARCHAR(45) NULL,
  `payment_payment_id` INT NOT NULL,
  `payment_user_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payment type_payment1_idx` (`payment_payment_id` ASC, `payment_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment type_payment1`
    FOREIGN KEY (`payment_payment_id` , `payment_user_id`)
    REFERENCES `datamart_airbnb`.`payment` (`payment_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart_airbnb`.`Listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart_airbnb`.`Listing` (
  `listing_id` INT NOT NULL,
  `listing_starttime` DATETIME NULL,
  `listing_endtime` DATETIME NULL,
  `host_host_id` INT NOT NULL,
  `property_property_id` INT NOT NULL,
  PRIMARY KEY (`listing_id`),
  INDEX `fk_Listing_host1_idx` (`host_host_id` ASC) VISIBLE,
  INDEX `fk_Listing_property1_idx` (`property_property_id` ASC) VISIBLE,
  CONSTRAINT `fk_Listing_host1`
    FOREIGN KEY (`host_host_id`)
    REFERENCES `datamart_airbnb`.`host` (`host_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Listing_property1`
    FOREIGN KEY (`property_property_id`)
    REFERENCES `datamart_airbnb`.`property` (`property_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
